spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transport_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: 9a4f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f
    expiration: 86400000 # 24 hours

app:
  maps:
    api-key: ${MAPS_API_KEY:default_maps_key_for_development}
logging:
  level:
    org:
      springframework:
        security=DEBUG: